-- 코드를 입력하세요
# SELECT a.FLAVOR
# from FIRST_HALF as a JOIN ICECREAM_INFO as b
# where a.TOTAL_ORDER > 3000 and b.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY a.TOTAL_ORDER desc

SELECT a.FLAVOR
FROM FIRST_HALF as a
JOIN ICECREAM_INFO as b
ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER > 3000
AND b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC;